### ISSUE TITLE
formatting not respecting yaml spec 1.2 for Collections

### ISSUE THREAD

**Issue by kjgen** [neoclide/coc-yaml#66]
I have configure the `yaml.format.enable` to `true` and I'm using the Azure pipelines yaml schema. I also have the coc configuration format on save set to true. When I save the document, it indents my collection elements instead of keeping them on the same vertical line.
Example:
Before
```yml
steps:
- task: ABC
  inputs:
    test: hello
```
After formatting:
```yml
steps:
  - task: ABC
    inputs:
      test: hello
```

The formatting shouldn't change the indentation of the collection if we follow the yaml spec 1.2. Why is this happening?
